---

# tasks file for docker-install

- name: Debian Configure Sysctl
  sysctl:
    name: "net.ipv4.ip_forward"
    value: "1"
    state: present

- name: Debian Install Prerequisites Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Debian Add GPG Keys
  apt_key:
    url: "{{ docker_url_apt_key }}"

- name: Debian Add Repo Source
  apt_repository:
    repo: "{{ docker_repository }}"
    update_cache: yes

- name: Debian Install Latest version of Docker Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"
  notify: start docker

- name: Debian Start and Enable Docker Service
  service:
    name: docker
    state: started
    enabled: yes

