---
- name: Install Docker Server
  hosts: k8s
  become: true
  gather_facts: yes
  vars:
    docker_dependencies:
    - ca-certificates
    - gnupg
    - gnupg-agent
    - software-properties-common
    - apt-transport-https
    - gnupg2
    docker_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io 
    - curl
    docker_url_apt_key: "https://download.docker.com/linux/debian/gpg"
    docker_repository: "deb [arch=arm64] https://download.docker.com/linux/debian buster stable"
  tasks:
  - name: Debian | Configure Sysctl
    sysctl:
      name: "net.ipv4.ip_forward"
      value: "1"
      state: present

  - name: Debian | Install Prerequisites Packages
    package: name={{ item }} state=present force=yes
    loop: "{{ docker_dependencies }}"

  - name: Debian | Add GPG Keys
    apt_key: 
      url: "{{ docker_url_apt_key }}"

  - name: Debian | Add Repo Source
    apt_repository: 
      repo: "{{ docker_repository }}"
      update_cache: yes

  - name: Debian | Install Specific Version of Docker Packages
    package: name={{ item }} state=present force=yes install_recommends=no
    loop: "{{ docker_packages }}"
    notify:
    - start docker

  - name: Debian | Start and Enable Docker Service
    service:
      name: docker
      state: started
      enabled: yes  

  handlers:
  - name: start docker
    service: name=docker state=started
...
