---
# vars file for docker-install
docker_dependencies:
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gnupg
  - gnupg2
  - gnupg-agent
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - curl
docker_url_apt_key: "https://download.docker.com/linux/debian/gpg"
docker_repository: "deb [arch=arm64] https://download.docker.com/linux/debian buster stable"

